<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriaRepository extends EntityRepository {

    public function findAllOrderedByTopicName() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c FROM AppBundle:Criteria c JOIN c.topic t ORDER BY t.name, c.name ASC'
                        )
                        ->getResult();
    }
    
    public function findAllOrderedByName() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c FROM AppBundle:Criteria c ORDER BY c.name ASC'
                        )
                        ->getResult();
    }    

    /**
     * Return criterias filtered by $topicId, name
     * @param String $topicId
     * @param String $name
     * @return Criteria
     */
    public function findLike($topicId,$name) {

        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c FROM AppBundle:Criteria c JOIN c.topic t WHERE (t.id = :topicId) AND (c.name LIKE :filter) ORDER BY c.name ASC'
                        )
                        ->setParameter('topicId', $topicId)
                        ->setParameter('filter', '%' . $name . '%')
                        ->getResult();
    }
    
    
     /**
     * Find criterias by topicId
     * @param type $topicId
     * @return Array criteria
     */
    public function findByTopic($topicId) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c FROM AppBundle:Criteria c JOIN c.topic t WHERE t.id = :topicId ORDER BY c.name ASC'
                        )->setParameter('topicId', $topicId)
                        ->getResult();
    }

}
