<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository {

    public function findAllOrderedById() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT r FROM AppBundle:Review r ORDER BY r.id DESC'
                        )
                        ->getResult();
    }
    
     /**
     * Return reviews filtered by name(like)
     * @param String $name
     * @return Review
     */
    public function findLikeName($name) {

        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT r FROM AppBundle:Review r WHERE r.description LIKE :filter ORDER BY r.id DESC'
                        )->setParameter('filter', '%' . $name . '%')
                        ->getResult();
    }

}
