# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.paginator:
        class: AppBundle\Utils\Paginator
        arguments: [@service_container]
    app.review:
        class: AppBundle\Services\ReviewService   
        arguments: [ @doctrine.orm.entity_manager, @request_stack ]
    app.positive:
        class: AppBundle\Services\PositiveAttributeService   
        arguments: [ @doctrine.orm.entity_manager, @request_stack ]      
    app.negative:
        class: AppBundle\Services\NegativeAttributeService   
        arguments: [ @doctrine.orm.entity_manager, @request_stack ]   
    app.topic:
        class: AppBundle\Services\TopicService   
        arguments: [ @doctrine.orm.entity_manager, @request_stack ]     
    app.criteria:
        class: AppBundle\Services\CriteriaService   
        arguments: [ @doctrine.orm.entity_manager, @request_stack ] 
    app.separator:
        class: AppBundle\Services\SeparatorService   
        arguments: [ @doctrine.orm.entity_manager ]               
